"""add composite index on chat_sessions (agent_id, updated_at)

Revision ID: 18dc41cd0a7a
Revises: d07766a6c84d
Create Date: 2026-06-28 18:07:30.856490

"""

from collections.abc import Sequence

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "18dc41cd0a7a"
down_revision: str | Sequence[str] | None = "d07766a6c84d"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_chat_sessions_agent_id"), table_name="chat_sessions")
    op.create_index("ix_chat_sessions_agent_updated", "chat_sessions", ["agent_id", "updated_at"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_chat_sessions_agent_updated", table_name="chat_sessions")
    op.create_index(op.f("ix_chat_sessions_agent_id"), "chat_sessions", ["agent_id"], unique=False)
    # ### end Alembic commands ###
